FROM registry.access.redhat.com/ubi9/ubi:latest as builder

ADD . /go/src/github.com/guacsec/guac/
WORKDIR /go/src/github.com/guacsec/guac/
RUN dnf install -y go-toolset jq https://github.com/goreleaser/goreleaser/releases/download/v1.19.2/goreleaser-1.19.2.x86_64.rpm
RUN rm -rf bin/ && make build


FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
RUN microdnf install -y tar gzip
WORKDIR /root
COPY --from=builder /go/src/github.com/guacsec/guac/bin/ /opt/guac/
