FROM docker.io/library/golang:1.19 as builder
ADD . /go/src/github.com/guacsec/guac/
WORKDIR /go/src/github.com/guacsec/guac/
RUN rm -rf bin/ && make build

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
RUN microdnf install -y tar gzip
WORKDIR /root
COPY --from=builder /go/src/github.com/guacsec/guac/bin/ /opt/guac/
